version: '3.9'

services:
  dbase:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123word
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  django:
    build:
      context: ./django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/usr/src/djapp/
    ports:
      - "8000:8000"
    depends_on:
      - dbase
    environment:
      - DATABASE_URL=postgres://postgres:pass123word@dbase:5432/postgres

  fastapi:
    build:
      context: ./fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --reload
    volumes:
      - ./fastapi_app:/usr/src/fastapp/
    ports:
      - "9400:9400"
    depends_on:
      - dbase
    environment:
      - DATABASE_URL=postgres://postgres:pass123word@dbase:5432/postgres
